apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    myapp: webapp
    release: "1.0"
spec:
  containers:
  - name: webapp
    image: nitinji85/myrepo:microservice-1.0

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-2.0
  labels:
    myapp: webapp
    release: "2.0"
spec:
  containers:
  - name: webapp
    image: nitinji85/myrepo:microservice-2.0


