apiVersion: v1
kind: Service
metadata:
  name: sample-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    myapp: webapp
    release: "1.0"

  ports:
    - name: http
      port: 9080
      nodePort: 30080

  type: NodePort
